# 本地环境配置文件
spring:
  datasource:
    hikari:
      connection-timeout: 30000
      max-lifetime: 600000
      pool-name: XCodeHikariCP
      minimum-idle: 1
      maximum-pool-size: 2
      idle-timeout: 30000
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        # 主库数据源
        master:
          driver-class-name: oracle.jdbc.driver.OracleDriver
          url: jdbc:oracle:thin:@172.31.0.45:1521/dghb
          username: basecenter
          password: basecenter
        outwater:
          # 从数据源开关/默认关闭
          driver-class-name: oracle.jdbc.driver.OracleDriver
          url: jdbc:oracle:thin:@172.31.0.45:1521/dghb
          username: paishuihu
          password: paishuihu

        lwjh:
          # 从数据源开关/默认关闭
          driver-class-name: oracle.jdbc.driver.OracleDriver
          url: jdbc:oracle:thin:@172.31.0.45:1521/dghb
          username: lianwangjihua
          password: lianwangjihua

        guocheng:
          # 从数据源开关/默认关闭
          driver-class-name: oracle.jdbc.driver.OracleDriver
          url: jdbc:oracle:thin:@172.31.0.45:1521/dghb
          username: hbgc
          password: hbgc

        voc:
          # 从数据源开关/默认关闭
          driver-class-name: oracle.jdbc.driver.OracleDriver
          url: jdbc:oracle:thin:@172.31.0.45:1521/dghb
          username: voc
          password: voc

        youyan:
          # 从数据源开关/默认关闭
          driver-class-name: oracle.jdbc.driver.OracleDriver
          url: jdbc:oracle:thin:@172.31.0.45:1521/dghb
          username: youyan
          password: youyan

        jiayou:
          # 从数据源开关/默认关闭
          driver-class-name: oracle.jdbc.driver.OracleDriver
          url: jdbc:oracle:thin:@172.31.0.45:1521/dghb
          username: jiayou
          password: jiayou

        qixiu:
          # 从数据源开关/默认关闭
          driver-class-name: oracle.jdbc.driver.OracleDriver
          url: jdbc:oracle:thin:@172.31.0.45:1521/dghb
          username: qixiu
          password: qixiu

        jinshu:
          # 从数据源开关/默认关闭
          driver-class-name: oracle.jdbc.driver.OracleDriver
          url: jdbc:oracle:thin:@172.31.0.45:1521/dghb
          username: jinshu
          password: jinshu

        lingxing:
          driver-class-name: oracle.jdbc.driver.OracleDriver
          url: jdbc:oracle:thin:@172.31.0.45:1521/dghb
          username: lingxing
          password: lingxing

        zaozhi:
          # 从数据源开关/默认关闭
          driver-class-name: oracle.jdbc.driver.OracleDriver
          url: jdbc:oracle:thin:@172.31.0.45:1521/dghb
          username: zaozhi
          password: zaozhi

        hbonline:
          # 从数据源开关/默认关闭
          driver-class-name: oracle.jdbc.driver.OracleDriver
          url: jdbc:oracle:thin:@192.168.10.201:1521/dghb
          username: hbonline
          password: abc123...
        # 是否开启sql日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
