# 开发环境配置
server:
    # 服务器的HTTP端口，默认为8080
    port: 8989
    servlet:
        # 应用的访问路径
        context-path: /
    tomcat:
        # tomcat的URI编码
        uri-encoding: UTF-8
# 日志配置
logging:
    level:
        com.project: debug
        org.springframework: warn
# Spring配置
spring:
    profiles:
        active: prod
    # 文件上传
    servlet:
        multipart:
            # 单个文件大小
            max-file-size: 10MB
            # 设置总上传的文件大小
            max-request-size: 20MB
    # 服务模块
    devtools:
        restart:
            # 热部署开关
            enabled: true
# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌秘钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）
    expireTime: 120

# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.topcent.project.**.model
    # 配置mapper的扫描,找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mybatis/mapper/*.*
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml
